vault_token: "{{ lookup('ansible.builtin.env', 'VAULT_TOKEN', default=undef() ) }}"
vault_url: "{{  lookup('ansible.builtin.env', 'VAULT_ADDR', default=undef() ) }}"

# These will be added into the allowed_domains for the certificates that require DNS names
# Namely, these are 
# ETCD
# - cn=kube-etcd
# - cn=kube-etcd-peer
# Kubernetes
# - cn=kube-apiserver

kubernetes_dns_endpoints: []
etcd_dns_endpoints: []
  
kubernetes_engine_path: "x509/kubernetes"
etcd_engine_path: "x509/etcd"
front_proxy_engine_path: "x509/front-proxy"
serviceaccount_engine_path: "x509/serviceaccount"


# Extra policies to define, for fun and science.
extra_policies:
  - name: kubernetes_master
    path: "x509/kubernetes/kubernetes_master"
    certificates:
    - 

# Unless you're really curious, you can leave the options below as default. 
# They're fairly sane...
#
# ...fairly

#### Certificate authority options ####
vault_main_ca_options: &vault_main_ca_options
  ttl: "87600h" #10 years
  key_type: ed25519 #Smol certs

vault_kubernetes_ca_options:
  <<: *vault_main_ca_options
  common_name: "kubernetes-ca"
  alt_names: "kubernetes"

vault_etcd_ca_options:
  <<: *vault_main_ca_options
  common_name: "etcd-ca"
  alt_names: "etcd"

vault_front_proxy_ca_options:
  <<: *vault_main_ca_options
  common_name: "kubernetes-front-proxy-ca"
  alt_names: "front-proxy-ca"

#### Certificate Role options ####

vault_main_cert_role_options: &vault_main_cert_role_options
  ttl: "130h" # 1 month 
  server_flag: false
  client_flag: false
  key_type: ed25519

vault_etcd_domains: "{{ groups['etcd_servers']  + ['localhost'] + etcd_dns_endpoints }}"
vault_kubernetes_domains: "{{ groups['kubernetes_servers'] + ['localhost','kubernetes','kubernetes.default','kubernetes.default.svc','kubernetes.default.svc.cluster','kubernetes.default.svc.cluster.local'] + kubernetes_dns_endpoints }}"

# ETCD Certificate Authority
vault_etcd_cert_roles:
  kube_etcd:
    <<: *vault_main_cert_role_options
    #common_name: "kube-etcd"
    server_flag: true
    client_flag: true
    allowed_domains: "{{ vault_etcd_domains }}"
    
  kube_etcd_peer:
    <<: *vault_main_cert_role_options
    #common_name: "kube-etcd-peer"
    server_flag: true
    client_flag: true
    allowed_domains: "{{ vault_etcd_domains }}"

  kube_etcd_healthcheck_client:
    <<: *vault_main_cert_role_options
    #common_name: "kube-etcd-healthcheck-client"
    client_flag: true

  kube_apiserver_etcd_client:
    <<: *vault_main_cert_role_options
    #common_name: "kube-apiserver-etcd-client"
    client_flag: true
    organization: "system:masters"
  
# Main Kubernetes Certificate Authority
vault_kubernetes_cert_roles:
  kube_apiserver:
    <<: *vault_main_cert_role_options
    #common_name: "kube-apiserver"
    server_flag: true
    allowed_domains: "{{ vault_kubernetes_domains }}"

  kube_apiserver_kubelet_client:
    <<: *vault_main_cert_role_options
    #common_name: "kube-apiserver-kubelet-client"
    client_flag: true
    organization: "system:masters"

# The Front Proxy Certificate Authority
vault_front_proxy_cert_roles:
  front_proxy_client:
    <<: *vault_main_cert_role_options
    #common_name: "front-proxy-client"
    client_flag: true