
  # vars:
  #   vault_ca_path: "sou/kubernetes"
  #   vault_role_name: "admin"
  #   vault_org: "system:masters"
  # tasks:
- name: "Create a Certificate Role: {{ vault_role_name }}"
  ansible.builtin.include_role:
    name: "vault/certificates"
  vars:
    vault_cert_name: "{{ vault_role_name }}"
    vault_cert_max_ttl: "720h"
    vault_cert_ttl: "2d"
    component: "engine"
    state: "present"

- name: "Create a Policy: {{ vault_ca_path }}/issue/{{ vault_role_name }}"
  ansible.builtin.import_role:
    name: "vault/policies"
  vars:
    vault_policy_path: "{{ vault_ca_path }}/{{ vault_role_name }}"
    vault_policy_policies:
      - path: "{{ vault_ca_path }}/issue/{{ vault_role_name }}"
        capabilities:
          - "create"
          - "update"

- name: "Create a token Role: {{ vault_role_name }}"
  ansible.builtin.import_role:
    name: "vault/role-token"
  vars:
    vault_token_allowed_policies: ["{{ vault_ca_path }}/{{ vault_role_name }}"]
    vault_token_orphan: true
    vault_token_period: "720h"
    vault_token_role_name: "{{ vault_role_name }}"