- name: "Setup hashicorp vault"
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
  - vars.yaml
  tasks:
  - name: "Setup Reader role for each engine"
    ansible.builtin.include_role:
      name: "vault/certificate_policy"
    vars:
      vault_policy_path: "{{ item }}/read"
      vault_policy_policies:
      - path: "{{ item }}/certs"
        capabilities:
          - "list"
      - path: "{{ item }}/cert/*"
        capabilities:
          - "read"
    loop:
    - "{{ kubernetes_engine_path }}"
    - "{{ etcd_engine_path }}"
    - "{{ front_proxy_engine_path }}"

  - name: "Setup certificate policies for Kubernetes"
    ansible.builtin.include_role:
      name: "vault/certificate_policy"
    vars:
      vault_policy_path: "{{ kubernetes_engine_path }}/{{ item.key | replace('_','-') }}"
      vault_policy_policies:
      - path: "{{ kubernetes_engine_path }}/issue/{{ item.key | replace('_','-') }}"
        capabilities:
             - "create"
             - "update"
      # - path: "{{ kubernetes_engine_path }}/certs"
      #   capabilities:
      #     - "list"
      # - path: "{{ kubernetes_engine_path }}/cert/*"
      #   capabilities:
      #     - "read"
    loop: "{{ vault_kubernetes_cert_roles | dict2items }}"

  - name: "Setup certificate policies for ETCD"
    ansible.builtin.include_role:
      name: "vault/certificate_policy"
    vars:
      vault_policy_path: "{{ etcd_engine_path }}/{{ item.key | replace('_','-') }}"
      vault_policy_policies:
      - path: "{{ etcd_engine_path }}/issue/{{ item.key | replace('_','-') }}"
        capabilities:
             - "create"
             - "update"
      # - path: "{{ etcd_engine_path }}/certs"
      #   capabilities:
      #     - "list"
      # - path: "{{ etcd_engine_path }}/cert/*"
      #   capabilities:
      #     - "read"
    loop: "{{ vault_etcd_cert_roles | dict2items }}"


  - name: "Setup certificate policies for the Front Proxy"
    ansible.builtin.include_role:
      name: "vault/certificate_policy"
    vars:
      vault_policy_path: "{{ front_proxy_engine_path }}/{{ item.key | replace('_','-') }}"
      vault_policy_policies:
      - path: "{{ front_proxy_engine_path }}/issue/{{ item.key | replace('_','-') }}"
        capabilities:
             - "create"
             - "update"
      # - path: "{{ front_proxy_engine_path }}/certs"
      #   capabilities:
      #     - "list"
      # - path: "{{ front_proxy_engine_path }}/cert/*"
      #   capabilities:
      #     - "read"
    loop: "{{ vault_front_proxy_cert_roles | dict2items }}"