- name: "Setup hashicorp vault Certificate Authorities"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: "Setup Certificate Authority"
    ansible.builtin.include_role:
      name: "vault/certificate_authority"
    vars:
      vault_ca_path: "{{ item.value.path }}"
      vault_root_certificate_options:  "{{ item.value.certificate }}"
    loop: "{{ vault_pki_engines | dict2items }}"
