- name: "Setup hashicorp vault"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: "Setup certificate roles"
    ansible.builtin.include_role:
      name: "vault/certificate_roles"
    loop: "{{ vault_certificates | dict2items }}"
    vars:
      vault_role_name: "{{ item.value.role_name | default(item.key) }}"
      vault_ca_path: "{{ vault_pki_engines[item.value.ca].path }}"
      vault_cert_role_options: "{{ item.value.role }}"