- name: "Setup hashicorp vault"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: "Setup Certificate reader role for each engine"
    ansible.builtin.include_role:
      name: "vault/certificate_policy"
    vars:
      vault_engine_path: "{{ item.value.path }}"
      vault_policy_path: "{{ vault_engine_path }}/read"
      vault_policy_policies:
      - path: "{{ vault_engine_path }}/certs"
        capabilities:
          - "list"
      - path: "{{ vault_engine_path }}/cert/*"
        capabilities:
          - "read"
    loop: "{{ vault_pki_engines | dict2items }}"

  - name: "Setup certificate policies for Kubernetes"
    ansible.builtin.include_role:
      name: "vault/certificate_policy"
    vars:
      vault_role_name:  "{{ item.value.role_name | default(item.key) }}"
      vault_engine_path: "{{ vault_pki_engines[item.value.ca].path }}"
      vault_policy_path: "{{ vault_engine_path }}/{{ vault_role_name }}"
      vault_policy_policies:
      - path: "{{ vault_engine_path }}/issue/{{ vault_role_name }}"
        capabilities:
             - "create"
             - "update"
    loop: "{{ vault_certificates | dict2items }}"

  - name: "Setup certificate policies for KV Engines"
    ansible.builtin.include_role:
      name: "vault/certificate_policy"
    vars:
      vault_role_name:  "{{ item.key }}"
      vault_engine_path: "{{ vault_kv_engines[item.value.engine].path }}"
      vault_policy_path: "{{ vault_engine_path }}/{{ vault_role_name }}"
      vault_policy_policies:
      - path: "{{ vault_engine_path }}/data/{{ item.value.pubkey_path }}"
        capabilities:
             - "read"
      - path: "{{ vault_engine_path }}/data/{{ item.value.privkey_path }}"
        capabilities:
             - "read"
    loop: "{{ vault_pubkey_pairs | dict2items }}"