- name: "Setup hashicorp vault"
  hosts: aio
  connection: local
  gather_facts: false
  tasks:
  - debug:
      msg: "{{ inventory_hostname }}"
  - name: "Setup certificate roles for Kubernetes"
    ansible.builtin.include_role:
      name: "vault/consul_template"
