- name: "Setup hashicorp vault"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: "Setup Key value engines"
    ansible.builtin.include_role:
      name: "vault/key-value_engine"
    vars:
      vault_engine_path: "{{ item.value.path }}"
    loop: "{{ vault_kv_engines | dict2items }}"

  - name: "Setup Key value Keypairs"
    ansible.builtin.include_role:
      name: "vault/pubkey_pairs"
    vars:
      vault_engine_path: "{{ vault_kv_engines[item.value.engine].path }}"
      pubkey_path: "{{ item.value.pubkey_path }}"
      privkey_path: "{{ item.value.privkey_path }}"
    loop: "{{ vault_pubkey_pairs | dict2items }}"