- name: "Setup hashicorp vault"
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
  - vars.yaml
  tasks:
  - name: "Setup Certificate Authorities for Kubernetes"
    ansible.builtin.include_role:
      name: "vault/service_account"
    vars:
      vault_engine_path: "{{ serviceaccount_engine_path }}"
      vault_engine_description: "Service account Secrets engine"
